# version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hyperleagal:latest
    container_name: hyperleagal
    restart: unless-stopped
    command:
      - /bin/sh
      - -c 
      - |
        npx prisma generate
        npm run start:dev
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app:rw
    depends_on:
      - db
      - dynamodb
    environment:
      - NODE_ENV=development
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    networks:
      - wanzy
  

  db:
    image: postgres:18
    container_name: postgres_db
    restart: unless-stopped 
    environment:
      POSTGRES_USER: hyperlegal 
      POSTGRES_PASSWORD: hyperlegal 
      POSTGRES_DB: hyperlegal 
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432" 
    volumes:
      - postgres_dbdata:/var/lib/postgresql/18/docker
    networks:
      - wanzy
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb_local
    restart: unless-stopped
    ports:
      - "8000:8000"
    # command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamoDB_data:/home/dynamodblocal/data
    networks:
      - wanzy
  localstack:
    image: localstack/localstack
    container_name: localstack
    restart: unless-stopped
    ports:
    - "4566:4566"
    volumes:
    - localstack_data:/var/lib/localstack
    networks:
    - wanzy
  
networks:
  wanzy:
    name: wanzy
    external: true
volumes:
  postgres_dbdata:
  dynamoDB_data:
  localstack_data:
